version: '2'
services:
  web:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/groupproject/autoapp
      - /usr/groupproject/autoapp/node_modules
    ports:
      - "4000:5000"
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: car_app
      POSTGRES_HOST: postgres-db
  postgres-db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: car_app
