version: '2'
services:
  web:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/groupproject/autoapp
      - /usr/groupproject/autoapp/node_modules
      - npm-cache:/root/.npm
    ports:
      - "4000:5000"
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: car_app
      POSTGRES_HOST: postgres-db
  postgres-db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: car_app
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - postgres-db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dev@dev.com
  #     PGADMIN_DEFAULT_PASSWORD: dev
  #   ports:
  #     - "5050:80"
  #   restart: always
  #   restart: unless-stopped
volumes:
  npm-cache:
    external: false