version: '2'
services:
  web:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/groupproject/autoapp
      - /usr/groupproject/autoapp/node_modules
    ports:
      - "4000:5000"
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root@postgres/autoapp
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: autoapp
      POSTGRES_DB: autoapp
